bookStoreWeb/Areas/Admin/Controllers/CompanyController.cs
using BookStoreWeb.data;
using BookStoreWeb.data.Repository.IRepository;
using BookStoreWeb.Models;
using BookStoreWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace bookStoreWeb.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _db;
     

        public CompanyController(IUnitOfWork db)
        {
            _db = db;
        }

        //GET Book
        public IActionResult Index()
        {
            IEnumerable<CompanyModel> companyList = _db.Company.GetAll();

            return View(companyList);
        }


        //Render Create Form
        [HttpGet]
        public IActionResult Upsert(int id)
        {
            CompanyModel company = new();

            if (id == null || id == 0)
            {
                //Create
                return View(company);
            }
            else
            {
                company = _db.Company.GetFirstOrDefault(u => u.Id == id);
                return View(company);
            }

        }

        //Post Created/Edited Form
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(CompanyModel obj)
        {
            if (ModelState.IsValid)
            {
               
               
                if (obj.Id == 0)
                {

                    _db.Company.Add(obj);
                }
                else
                {
                    _db.Company.Update(obj);
                }
                _db.Save();
                TempData["Success"] = "Company successfully created";
                return RedirectToAction("Index");
            }
            return Upsert(obj);
        }

        #region API End points

        public IActionResult getAll()
        {
            var companyList = _db.Company.GetAll();
            return Json(new { data = companyList });
        }


        [HttpGet]// httpget for delete because to retreive ID from params..
        public IActionResult Delete(int? id)
        {
            var userDetails = _db.Company.GetFirstOrDefault(item => item.Id == id);
            if (userDetails == null)
            {
                return Json(new { Error = true, message = "Error while deleting" });
            }
            _db.Company.Remove(userDetails);
            _db.Save();
            return Json(new { Error = false, message = "Delete success" });
        }
        #endregion

    }
}

bookStoreWeb/Areas/Admin/Controllers/OrderController.cs
using BookStoreWeb.data.Repository.IRepository;
using BookStoreWeb.Models;
using BookStoreWeb.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(string status)
        {
            IEnumerable<OrderHeader> orderHeaders =  _unitOfWork.OrderHeader.GetAll(includeProp: "ApplicationUser");
            switch (status)
            {
                case "pending":
                    orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.PaymentStatusDelayedPayment);
                    break;
                case "inprocess":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusInProcess);
                    break;
                case "completed":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusApproved);
                    break;
                default:
                    break;
            }
            return View(orderHeaders);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> orderHeaders;

            //if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
            //{
            orderHeaders = _unitOfWork.OrderHeader.GetAll(includeProp: "ApplicationUser");
            //}
            //else
            //{
            //    var claimsIdentity = (ClaimsIdentity)User.Identity;
            //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //    orderHeaders = _unitOfWork.OrderHeader.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "ApplicationUser");
            //}

            switch (status)
            {
                case "pending":
                    orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.PaymentStatusDelayedPayment);
                    break;
                case "inprocess":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusInProcess);
                    break;
                case "completed":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusApproved);
                    break;
                default:
                    break;
            }


            return Json(new { data = orderHeaders });
        }
        #endregion
    }
}

bookStoreWeb/Areas/Admin/Controllers/ProductController.cs
using BookStoreWeb.data;
using BookStoreWeb.data.Repository.IRepository;
using BookStoreWeb.Models;
using BookStoreWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace bookStoreWeb.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork db, IWebHostEnvironment hostEnv)
        {
            _db = db;
            _webHostEnvironment = hostEnv;
        }

        //GET Book
        public IActionResult Index()
        {
            IEnumerable<ProductModel> productList = _db.Products.GetAll(includeProp: "Category,CoverType");

            return View(productList);
        }


        //Render Create Form
        [HttpGet]
        public IActionResult Upsert(int id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _db.Category.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                CoverTypeList = _db.CoverType.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
            };

            if (id == null || id == 0)
            {
                //Create
                return View(productVM);
            }
            else
            {
                ProductModel product = _db.Products.GetFirstOrDefault(u => u.Id == id);
                productVM.Product = product;
                return View(productVM);
            }

        }

        //Post Created/Edited Form
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"Images\Products");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImageUrl = Path.Combine(wwwRootPath, obj.Product.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(oldImageUrl))
                        {
                            System.IO.File.Delete(oldImageUrl);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams); //filestream is the stream created to copy the file and save it in the given location(wwwroot)
                    }

                    obj.Product.ImageUrl = @"\Images\Products\" + fileName + extension;
                }
                if (obj.Product.Id == 0)
                {

                    _db.Products.Add(obj.Product);
                }
                else
                {
                    _db.Products.Update(obj.Product);
                }
                _db.Save();
                TempData["Success"] = "Category successfully created";
                return RedirectToAction("Index");
            }
            return Upsert(obj.Product.Id);
        }

        #region API End points

        public IActionResult getAll()
        {
            var productList = _db.Products.GetAll(includeProp: "Category,CoverType");
            return Json(new { data = productList });
        }
        [HttpGet]// httpget for delete because to retreive ID from params..
        public IActionResult Delete(int? id)
        {
            var userDetails = _db.Products.GetFirstOrDefault(item => item.Id == id);
            if (userDetails == null)
            {
                return Json(new { Error = true, message = "Error while deleting" });
            }

            var oldImageUrl = Path.Combine(_webHostEnvironment.WebRootPath, userDetails.ImageUrl.Trim('\\'));
            if (System.IO.File.Exists(oldImageUrl))
            {
                System.IO.File.Delete(oldImageUrl);
            }

            _db.Products.Remove(userDetails);
            _db.Save();
            return Json(new { Error = false, message = "Delete success" });
        }
        #endregion

    }
}

bookStoreWeb/Controllers/CategoryController.cs
using BookStoreWeb.Data;
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace bookStoreWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET Book
        public IActionResult Index()
        {
            IEnumerable<Category> categoryList = _db.Categories;

            return View(categoryList);
        }

        //Get Book
        public IActionResult Create()
        {
            return View();
        }

        //Post Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Display Order cannot be Name");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["Success"] = "Category successfully created";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get Edit Book
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFrmDb = _db.Categories.Find(id);

            return View(categoryFrmDb);
        }

        //Post Edited Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            var userDetails = _db.Categories.AsNoTracking().Where(u => u.Name == obj.Name).ToList();
            if (userDetails.Count>=2)
            {
                ModelState.AddModelError("name", "Name already exist, Choose different Name");

            }
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Display Order cannot be Name");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["Success"] = "Category successfully edited";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //Get Edit Book
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFrmDb = _db.Categories.Find(id);

            return View(categoryFrmDb);
        }

        //Post Edited Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var userDetails = _db.Categories.Find(id);
            if (userDetails == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(userDetails);
            _db.SaveChanges();
            _db.Dispose();
            TempData["Success"] = "Category successfully deleted";
            return RedirectToAction("Index");

        }

    }
}

bookStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bookStoreWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bookStoreWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">CMS</a>
                            <div class="dropdown-menu">
                                <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="nav-link" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                <a class="nav-link" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class=nav-link asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                cart
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index">
                                Manage Order
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-dark">
        <div class="container">
            &copy; 2022 - bookStoreWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

bookStoreWeb/Views/Shared/_Notification.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (TempData["Success"] != null)
    {
        <h2>@TempData["Success"]</h2>
    }

@if (TempData["Error"] != null)
    {
        <h2>@TempData["Error"]</h2>
    }