bookStoreWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BookStoreWeb.data;
using BookStoreWeb.data.Repository.IRepository;
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace bookStoreWeb.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _db;

        public CoverTypeController(IUnitOfWork db)
        {
            _db = db;
        }

        //GET Book
        public IActionResult Index()
        {
            IEnumerable<CoverTypeModel> categoryList = _db.CoverType.GetAll();

            return View(categoryList);
        }

        //Get Book
        public IActionResult Create()
        {
            return View();
        }

        //Post Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverTypeModel obj)
        {

            if (ModelState.IsValid)
            {
                _db.CoverType.Add(obj);
                _db.Save();
                TempData["Success"] = "CoverType successfully created";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get Edit Book
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFrmDb = _db.Categories.Find(id);
            var categoryFrmDb = _db.CoverType.GetFirstOrDefault(item => item.Id == id);

            return View(categoryFrmDb);
        }

        //Post Edited Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverTypeModel obj)
        {
            List<CoverTypeModel> userDetails = _db.CoverType.GetRepo().Where(u => u.Name == obj.Name).ToList();
            if (userDetails.Count >= 2)
            {
                ModelState.AddModelError("name", "Name already exist, Choose different Name");
            }


            if (ModelState.IsValid)
            {

                _db.CoverType.Update(obj);
                _db.Save();
                TempData["Success"] = "CoverType successfully edited";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //Get Edit Book
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFrmDb = _db.CoverType.GetFirstOrDefault(item => item.Id == id);

            return View(categoryFrmDb);
        }

        //Delete Edited Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var userDetails = _db.CoverType.GetFirstOrDefault(item => item.Id == id);
            if (userDetails == null)
            {
                return NotFound();
            }
            _db.CoverType.Remove(userDetails);
            _db.Save();
            TempData["Success"] = "CoverType successfully deleted";
            return RedirectToAction("Index");

        }

    }
}

bookStoreWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverTypeModel


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb2">
            <h2>Create Category</h2>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
       
        <button type="submit" class="btn btn-warning" style="width:150px">create</button>
        <a asp-area="Admin" asp-controller="CoverType" asp-action="Index" class="btn btn-light" style="width:150px">Back</a>
    </div>
</form>

@section scripts{
    @{
        <partial name="_validationscriptspartial" />
    }
}

bookStoreWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverTypeModel


<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb2">
            <h2>Delete Category</h2>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
       
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-area="Admin" asp-controller="CoverType" asp-action="Index" class="btn btn-light" style="width:150px">Back</a>
    </div>
</form>

@section scripts{
    @{
        <partial name="_validationscriptspartial" />
    }
}

bookStoreWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverTypeModel


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb2">
            <h2>Edit Category</h2>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
      
        <button type="submit" class="btn btn-warning" style="width:150px">Update</button>
        <a asp-area="Admin" asp-controller="CoverType" asp-action="Index" class="btn btn-light" style="width:150px">Back</a>
    </div>
</form>

@section scripts{
    @{
        <partial name="_validationscriptspartial" />
    }
}

bookStoreWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverTypeModel>
@{
    ViewData["Title"] = "Index";
}
<partial name="_Notification"/>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1>Cover Type Index<h1>
        </div>
        <div class="col-6 text-end">
            <a asp-area="Admin" asp-controller="CoverType" asp-action="Create" class="btn btn-warning">Add Cover Type</a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr><th>Cover type name</th></tr>
    </thead>
    <tbody>
        <form method="post">
        @foreach (var obj in Model)
        {
            <tr>
                <td style="width:50%">@obj.Name</td>
                <td style="width:50%">
                    <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-warning">Edit</a>
                </td>
                <td style="width:50%">
                    <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-light">Delete</a>
                </td>
            </tr>
        }
        </form>
    </tbody>
</table>